config/routes.rb
Rails.application.routes.draw do
  resources :teacher_offices
  resources :teacher_data
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/teacher_datum.rb
class TeacherDatum < ApplicationRecord
end

app/models/teacher_office.rb
class TeacherOffice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/teacher_data_controller.rb
class TeacherDataController < ApplicationController
  before_action :set_teacher_datum, only: %i[ show edit update destroy ]

  # GET /teacher_data or /teacher_data.json
  def index
    @teacher_data = TeacherDatum.all
  end

  # GET /teacher_data/1 or /teacher_data/1.json
  def show
  end

  # GET /teacher_data/new
  def new
    @teacher_datum = TeacherDatum.new
  end

  # GET /teacher_data/1/edit
  def edit
  end

  # POST /teacher_data or /teacher_data.json
  def create
    @teacher_datum = TeacherDatum.new(teacher_datum_params)

    respond_to do |format|
      if @teacher_datum.save
        format.html { redirect_to @teacher_datum, notice: "Teacher datum was successfully created." }
        format.json { render :show, status: :created, location: @teacher_datum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teacher_data/1 or /teacher_data/1.json
  def update
    respond_to do |format|
      if @teacher_datum.update(teacher_datum_params)
        format.html { redirect_to @teacher_datum, notice: "Teacher datum was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher_datum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teacher_data/1 or /teacher_data/1.json
  def destroy
    @teacher_datum.destroy
    respond_to do |format|
      format.html { redirect_to teacher_data_url, notice: "Teacher datum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher_datum
      @teacher_datum = TeacherDatum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_datum_params
      params.require(:teacher_datum).permit(:first_name, :last_name, :nine_hundred, :email)
    end
end

app/controllers/teacher_offices_controller.rb
class TeacherOfficesController < ApplicationController
  before_action :set_teacher_office, only: %i[ show edit update destroy ]

  # GET /teacher_offices or /teacher_offices.json
  def index
    @teacher_offices = TeacherOffice.all
  end

  # GET /teacher_offices/1 or /teacher_offices/1.json
  def show
  end

  # GET /teacher_offices/new
  def new
    @teacher_office = TeacherOffice.new
  end

  # GET /teacher_offices/1/edit
  def edit
  end

  # POST /teacher_offices or /teacher_offices.json
  def create
    @teacher_office = TeacherOffice.new(teacher_office_params)

    respond_to do |format|
      if @teacher_office.save
        format.html { redirect_to @teacher_office, notice: "Teacher office was successfully created." }
        format.json { render :show, status: :created, location: @teacher_office }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teacher_offices/1 or /teacher_offices/1.json
  def update
    respond_to do |format|
      if @teacher_office.update(teacher_office_params)
        format.html { redirect_to @teacher_office, notice: "Teacher office was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher_office }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teacher_offices/1 or /teacher_offices/1.json
  def destroy
    @teacher_office.destroy
    respond_to do |format|
      format.html { redirect_to teacher_offices_url, notice: "Teacher office was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher_office
      @teacher_office = TeacherOffice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_office_params
      params.require(:teacher_office).permit(:building_name, :room_number, :floor_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teacher_data_helper.rb
module TeacherDataHelper
end

app/helpers/teacher_offices_helper.rb
module TeacherOfficesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>University</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/teacher_data/_form.html.erb
<%= form_with(model: teacher_datum) do |form| %>
  <% if teacher_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher_datum.errors.count, "error") %> prohibited this teacher_datum from being saved:</h2>

      <ul>
        <% teacher_datum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :nine_hundred %>
    <%= form.number_field :nine_hundred %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teacher_data/edit.html.erb
<h1>Editing Teacher Datum</h1>

<%= render 'form', teacher_datum: @teacher_datum %>

<%= link_to 'Show', @teacher_datum %> |
<%= link_to 'Back', teacher_data_path %>

app/views/teacher_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teacher Data</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Nine hundred</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teacher_data.each do |teacher_datum| %>
      <tr>
        <td><%= teacher_datum.first_name %></td>
        <td><%= teacher_datum.last_name %></td>
        <td><%= teacher_datum.nine_hundred %></td>
        <td><%= teacher_datum.email %></td>
        <td><%= link_to 'Show', teacher_datum %></td>
        <td><%= link_to 'Edit', edit_teacher_datum_path(teacher_datum) %></td>
        <td><%= link_to 'Destroy', teacher_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher Datum', new_teacher_datum_path %>

app/views/teacher_data/new.html.erb
<h1>New Teacher Datum</h1>

<%= render 'form', teacher_datum: @teacher_datum %>

<%= link_to 'Back', teacher_data_path %>

app/views/teacher_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @teacher_datum.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher_datum.last_name %>
</p>

<p>
  <strong>Nine hundred:</strong>
  <%= @teacher_datum.nine_hundred %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher_datum.email %>
</p>

<%= link_to 'Edit', edit_teacher_datum_path(@teacher_datum) %> |
<%= link_to 'Back', teacher_data_path %>

app/views/teacher_offices/_form.html.erb
<%= form_with(model: teacher_office) do |form| %>
  <% if teacher_office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher_office.errors.count, "error") %> prohibited this teacher_office from being saved:</h2>

      <ul>
        <% teacher_office.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :building_name %>
    <%= form.text_field :building_name %>
  </div>

  <div class="field">
    <%= form.label :room_number %>
    <%= form.number_field :room_number %>
  </div>

  <div class="field">
    <%= form.label :floor_number %>
    <%= form.number_field :floor_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teacher_offices/edit.html.erb
<h1>Editing Teacher Office</h1>

<%= render 'form', teacher_office: @teacher_office %>

<%= link_to 'Show', @teacher_office %> |
<%= link_to 'Back', teacher_offices_path %>

app/views/teacher_offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teacher Offices</h1>

<table>
  <thead>
    <tr>
      <th>Building name</th>
      <th>Room number</th>
      <th>Floor number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teacher_offices.each do |teacher_office| %>
      <tr>
        <td><%= teacher_office.building_name %></td>
        <td><%= teacher_office.room_number %></td>
        <td><%= teacher_office.floor_number %></td>
        <td><%= link_to 'Show', teacher_office %></td>
        <td><%= link_to 'Edit', edit_teacher_office_path(teacher_office) %></td>
        <td><%= link_to 'Destroy', teacher_office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher Office', new_teacher_office_path %>

app/views/teacher_offices/new.html.erb
<h1>New Teacher Office</h1>

<%= render 'form', teacher_office: @teacher_office %>

<%= link_to 'Back', teacher_offices_path %>

app/views/teacher_offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building name:</strong>
  <%= @teacher_office.building_name %>
</p>

<p>
  <strong>Room number:</strong>
  <%= @teacher_office.room_number %>
</p>

<p>
  <strong>Floor number:</strong>
  <%= @teacher_office.floor_number %>
</p>

<%= link_to 'Edit', edit_teacher_office_path(@teacher_office) %> |
<%= link_to 'Back', teacher_offices_path %>